theme: jekyll-theme-minimal

title: Óscar Olveira Miniño
description: Portfolio profesional y documentación técnica de redes (CCNA)

markdown: kramdown
permalink: pretty

collections:
  ccna:
    output: true